var arr=['HTML','CSS','C#','Python','Java','C','JS','C++','React','Angualar']
var a=arr.pop();
console.log(a)
console.log(arr.length)
var rev=arr.reverse()
console.log(arr[8])
var sh=arr.shift()
console.log(sh)
console.log(arr.length)
var so=arr.sort()
console.log(so)
var pu=arr.push('DB')
console.log(pu)
console.log(arr)
console.log(arr.length)
var unsh=arr.unshift('AI')
console.log(unsh)
console.log(arr.length)
var sp=arr.splice(2,1,'OS','UNIX')
console.log(sp)
console.log(arr)
console.log(arr[5])
var sl=arr.slice(4,7)
console.log(sl)
console.log(arr)